language: generic
install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq emacs24-nox emacs24-el
  - cp -R . ~/.emacs.d
script:
  - emacs --version
  - make -C ~/.emacs.d -e SHELL=/bin/bash
